export const BUSINESS_TYPE_LABELS = {
  nail_art: {
    product: 'Nail Design', products: 'Nail Designs',
    delivery_option: 'Nail Kit Delivery', appointment: 'Nail Appointment',
    quiz_name: 'Nail Style Quiz', custom_order: 'Custom Nail Design',
    shop: 'Nail Shop', book_appointment: 'Book Nail Appointment',
  },
  mehendi: {
    product: 'Mehendi Design', products: 'Mehendi Designs',
    delivery_option: 'DIY Mehendi Kit', appointment: 'Artist Visit',
    quiz_name: 'Mehendi Style Quiz', custom_order: 'Custom Mehendi',
    shop: 'Mehendi Gallery', book_appointment: 'Book Artist Visit',
  },
  jewellery: {
    product: 'Jewellery Piece', products: 'Jewellery Collection',
    delivery_option: 'Home Delivery', appointment: 'Try & Buy',
    quiz_name: 'Jewellery Style Quiz', custom_order: 'Custom Design',
    shop: 'Jewellery Shop', book_appointment: 'Book Try & Buy',
  },
  cake: {
    product: 'Cake Design', products: 'Cake Designs',
    delivery_option: 'Home Delivery', appointment: 'Custom Order',
    quiz_name: null, custom_order: 'Custom Cake',
    shop: 'Cake Gallery', book_appointment: 'Place Custom Order',
  },
  makeup_artist: {
    product: 'Makeup Look', products: 'Makeup Looks',
    delivery_option: 'Kit Delivery', appointment: 'Makeup Session',
    quiz_name: 'Makeup Style Quiz', custom_order: 'Custom Makeup Look',
    shop: 'Portfolio', book_appointment: 'Book Makeup Session',
  },
  handmade_jewellery: {
    product: 'Jewellery Piece', products: 'Jewellery Collection',
    delivery_option: 'Home Delivery', appointment: 'Try & Buy',
    quiz_name: 'Jewellery Style Quiz', custom_order: 'Custom Jewellery',
    shop: 'Jewellery Shop', book_appointment: 'Book Try & Buy',
  },
  artificial_jewellery: {
    product: 'Jewellery Piece', products: 'Jewellery Collection',
    delivery_option: 'Home Delivery', appointment: 'Try & Buy',
    quiz_name: 'Jewellery Style Quiz', custom_order: 'Custom Order',
    shop: 'Jewellery Shop', book_appointment: 'Book Try & Buy',
  },
  boutique_clothing: {
    product: 'Outfit', products: 'Collection',
    delivery_option: 'Home Delivery', appointment: 'Try & Buy',
    quiz_name: 'Style Quiz', custom_order: 'Custom Outfit',
    shop: 'Boutique', book_appointment: 'Book Try & Buy',
  },
  saree_boutique: {
    product: 'Saree', products: 'Saree Collection',
    delivery_option: 'Home Delivery', appointment: 'Draping Session',
    quiz_name: 'Saree Style Quiz', custom_order: 'Custom Blouse Order',
    shop: 'Saree Boutique', book_appointment: 'Book Draping Session',
  },
  lehenga_boutique: {
    product: 'Lehenga', products: 'Lehenga Collection',
    delivery_option: 'Home Delivery', appointment: 'Try & Buy',
    quiz_name: 'Style Quiz', custom_order: 'Custom Lehenga',
    shop: 'Lehenga Boutique', book_appointment: 'Book Appointment',
  },
  ethnic_wear: {
    product: 'Design', products: 'Collection',
    delivery_option: 'Home Delivery', appointment: 'Fitting Session',
    quiz_name: 'Style Quiz', custom_order: 'Custom Design',
    shop: 'Ethnic Wear Studio', book_appointment: 'Book Fitting',
  },
  tattoo_artist: {
    product: 'Tattoo Design', products: 'Tattoo Designs',
    delivery_option: 'Stencil Kit', appointment: 'Tattoo Session',
    quiz_name: 'Tattoo Style Quiz', custom_order: 'Custom Tattoo Design',
    shop: 'Design Gallery', book_appointment: 'Book Tattoo Session',
  },
  personalized_gifts: {
    product: 'Gift Item', products: 'Gift Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Gift Finder Quiz', custom_order: 'Custom Gift Order',
    shop: 'Gift Store', book_appointment: 'Book Pick Up',
  },
  wedding_decorator: {
    product: 'Decor Package', products: 'Decor Packages',
    delivery_option: 'Setup & Delivery', appointment: 'Consultation',
    quiz_name: 'Decor Style Quiz', custom_order: 'Custom Decor Package',
    shop: 'Portfolio', book_appointment: 'Book Consultation',
  },
  home_baker: {
    product: 'Baked Item', products: 'Baked Goods',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: null, custom_order: 'Custom Bake Order',
    shop: 'Bakery', book_appointment: 'Book Pick Up',
  },
  hair_stylist: {
    product: 'Hair Style', products: 'Hair Styles',
    delivery_option: 'Kit Delivery', appointment: 'Hair Session',
    quiz_name: 'Hair Style Quiz', custom_order: 'Custom Hair Look',
    shop: 'Portfolio', book_appointment: 'Book Hair Session',
  },
  eyelash_artist: {
    product: 'Lash Style', products: 'Lash Styles',
    delivery_option: 'Kit Delivery', appointment: 'Lash Session',
    quiz_name: 'Lash Style Quiz', custom_order: 'Custom Lash Look',
    shop: 'Lash Gallery', book_appointment: 'Book Lash Session',
  },
  bridal_stylist: {
    product: 'Bridal Look', products: 'Bridal Looks',
    delivery_option: 'Kit Delivery', appointment: 'Bridal Session',
    quiz_name: 'Bridal Style Quiz', custom_order: 'Custom Bridal Look',
    shop: 'Bridal Portfolio', book_appointment: 'Book Bridal Session',
  },
  handmade_crafts: {
    product: 'Craft Item', products: 'Craft Collection',
    delivery_option: 'Home Delivery', appointment: 'Workshop',
    quiz_name: 'Style Quiz', custom_order: 'Custom Craft Order',
    shop: 'Craft Store', book_appointment: 'Book Workshop',
  },
  resin_art: {
    product: 'Resin Piece', products: 'Resin Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom Resin Order',
    shop: 'Resin Art Store', book_appointment: 'Book Pick Up',
  },
  crochet: {
    product: 'Crochet Item', products: 'Crochet Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom Crochet Order',
    shop: 'Crochet Store', book_appointment: 'Book Pick Up',
  },
  candle_brand: {
    product: 'Candle', products: 'Candle Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Candle Style Quiz', custom_order: 'Custom Candle Order',
    shop: 'Candle Shop', book_appointment: 'Book Pick Up',
  },
  handmade_soap: {
    product: 'Soap', products: 'Soap Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Skin Quiz', custom_order: 'Custom Soap Order',
    shop: 'Soap Shop', book_appointment: 'Book Pick Up',
  },
  handmade_skincare: {
    product: 'Skincare Product', products: 'Skincare Collection',
    delivery_option: 'Home Delivery', appointment: 'Skin Consultation',
    quiz_name: 'Skin Type Quiz', custom_order: 'Custom Skincare Order',
    shop: 'Skincare Shop', book_appointment: 'Book Consultation',
  },
  balloon_decoration: {
    product: 'Decor Package', products: 'Decor Packages',
    delivery_option: 'Setup & Delivery', appointment: 'Consultation',
    quiz_name: 'Decor Style Quiz', custom_order: 'Custom Decor Package',
    shop: 'Portfolio', book_appointment: 'Book Consultation',
  },
  florist: {
    product: 'Floral Arrangement', products: 'Floral Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Floral Style Quiz', custom_order: 'Custom Floral Order',
    shop: 'Flower Shop', book_appointment: 'Book Pick Up',
  },
  event_planner: {
    product: 'Event Package', products: 'Event Packages',
    delivery_option: 'On-site Setup', appointment: 'Consultation',
    quiz_name: 'Event Style Quiz', custom_order: 'Custom Event Package',
    shop: 'Portfolio', book_appointment: 'Book Consultation',
  },
  chocolate_bouquet: {
    product: 'Chocolate Bouquet', products: 'Chocolate Bouquets',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: null, custom_order: 'Custom Chocolate Bouquet',
    shop: 'Chocolate Shop', book_appointment: 'Book Pick Up',
  },
  return_gifts: {
    product: 'Gift Item', products: 'Gift Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Gift Finder Quiz', custom_order: 'Custom Gift Order',
    shop: 'Gift Store', book_appointment: 'Book Pick Up',
  },
  invitation_designer: {
    product: 'Invitation Design', products: 'Invitation Designs',
    delivery_option: 'Digital / Courier', appointment: 'Consultation',
    quiz_name: 'Style Quiz', custom_order: 'Custom Invitation',
    shop: 'Design Portfolio', book_appointment: 'Book Consultation',
  },
  custom_nameplate: {
    product: 'Nameplate', products: 'Nameplate Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: null, custom_order: 'Custom Nameplate Order',
    shop: 'Nameplate Store', book_appointment: 'Book Pick Up',
  },
  pottery: {
    product: 'Pottery Piece', products: 'Pottery Collection',
    delivery_option: 'Home Delivery', appointment: 'Workshop',
    quiz_name: 'Style Quiz', custom_order: 'Custom Pottery Order',
    shop: 'Pottery Store', book_appointment: 'Book Workshop',
  },
  clay_art: {
    product: 'Clay Art Piece', products: 'Clay Art Collection',
    delivery_option: 'Home Delivery', appointment: 'Workshop',
    quiz_name: 'Style Quiz', custom_order: 'Custom Clay Art Order',
    shop: 'Clay Art Store', book_appointment: 'Book Workshop',
  },
  digital_portrait: {
    product: 'Portrait Style', products: 'Portrait Styles',
    delivery_option: 'Digital Delivery', appointment: 'Consultation',
    quiz_name: 'Style Quiz', custom_order: 'Custom Portrait Order',
    shop: 'Portrait Gallery', book_appointment: 'Book Consultation',
  },
  home_decor: {
    product: 'Decor Piece', products: 'Decor Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Decor Style Quiz', custom_order: 'Custom Decor Order',
    shop: 'Decor Store', book_appointment: 'Book Pick Up',
  },
  wall_decor: {
    product: 'Wall Decor Piece', products: 'Wall Decor Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Decor Style Quiz', custom_order: 'Custom Wall Decor',
    shop: 'Wall Decor Store', book_appointment: 'Book Pick Up',
  },
  macrame: {
    product: 'Macrame Piece', products: 'Macrame Collection',
    delivery_option: 'Home Delivery', appointment: 'Workshop',
    quiz_name: 'Style Quiz', custom_order: 'Custom Macrame Order',
    shop: 'Macrame Store', book_appointment: 'Book Workshop',
  },
  furniture_decor: {
    product: 'Decor Piece', products: 'Decor Collection',
    delivery_option: 'Home Delivery', appointment: 'Consultation',
    quiz_name: 'Decor Style Quiz', custom_order: 'Custom Decor Order',
    shop: 'Decor Brand', book_appointment: 'Book Consultation',
  },
  fashion_accessories: {
    product: 'Accessory', products: 'Accessories Collection',
    delivery_option: 'Home Delivery', appointment: 'Try & Buy',
    quiz_name: 'Style Quiz', custom_order: 'Custom Accessory Order',
    shop: 'Accessories Store', book_appointment: 'Book Try & Buy',
  },
  handbag_brand: {
    product: 'Handbag', products: 'Handbag Collection',
    delivery_option: 'Home Delivery', appointment: 'Try & Buy',
    quiz_name: 'Style Quiz', custom_order: 'Custom Handbag Order',
    shop: 'Handbag Store', book_appointment: 'Book Try & Buy',
  },
  bridal_accessories: {
    product: 'Bridal Accessory', products: 'Bridal Accessories',
    delivery_option: 'Home Delivery', appointment: 'Try & Buy',
    quiz_name: 'Bridal Style Quiz', custom_order: 'Custom Bridal Accessory',
    shop: 'Bridal Accessories Store', book_appointment: 'Book Try & Buy',
  },
  custom_footwear: {
    product: 'Footwear Design', products: 'Footwear Collection',
    delivery_option: 'Home Delivery', appointment: 'Try & Buy',
    quiz_name: 'Style Quiz', custom_order: 'Custom Footwear Order',
    shop: 'Footwear Store', book_appointment: 'Book Try & Buy',
  },
  watch_accessories: {
    product: 'Accessory', products: 'Accessories Collection',
    delivery_option: 'Home Delivery', appointment: 'Try & Buy',
    quiz_name: 'Style Quiz', custom_order: 'Custom Order',
    shop: 'Accessories Store', book_appointment: 'Book Try & Buy',
  },
  dessert_business: {
    product: 'Dessert', products: 'Dessert Menu',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: null, custom_order: 'Custom Dessert Order',
    shop: 'Dessert Shop', book_appointment: 'Book Pick Up',
  },
  donut_shop: {
    product: 'Donut', products: 'Donut Menu',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: null, custom_order: 'Custom Donut Box',
    shop: 'Donut Shop', book_appointment: 'Book Pick Up',
  },
  macaron_business: {
    product: 'Macaron', products: 'Macaron Menu',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: null, custom_order: 'Custom Macaron Box',
    shop: 'Macaron Shop', book_appointment: 'Book Pick Up',
  },
  mithai_sweets: {
    product: 'Sweet', products: 'Sweets Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: null, custom_order: 'Custom Sweet Box',
    shop: 'Sweet Boutique', book_appointment: 'Book Pick Up',
  },
  gift_hamper: {
    product: 'Gift Hamper', products: 'Gift Hampers',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Gift Finder Quiz', custom_order: 'Custom Gift Hamper',
    shop: 'Gift Hamper Store', book_appointment: 'Book Pick Up',
  },
  festival_gifts: {
    product: 'Gift Item', products: 'Festival Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Gift Finder Quiz', custom_order: 'Custom Gift Order',
    shop: 'Festival Gift Store', book_appointment: 'Book Pick Up',
  },
  rakhi_business: {
    product: 'Rakhi', products: 'Rakhi Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: null, custom_order: 'Custom Rakhi Order',
    shop: 'Rakhi Store', book_appointment: 'Book Pick Up',
  },
  diwali_hamper: {
    product: 'Diwali Hamper', products: 'Diwali Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: null, custom_order: 'Custom Diwali Hamper',
    shop: 'Diwali Store', book_appointment: 'Book Pick Up',
  },
  scrapbook: {
    product: 'Scrapbook', products: 'Scrapbook Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom Scrapbook Order',
    shop: 'Scrapbook Store', book_appointment: 'Book Pick Up',
  },
  memory_album: {
    product: 'Memory Album', products: 'Album Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom Album Order',
    shop: 'Album Studio', book_appointment: 'Book Pick Up',
  },
  handmade_toys: {
    product: 'Toy', products: 'Toy Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: null, custom_order: 'Custom Toy Order',
    shop: 'Toy Store', book_appointment: 'Book Pick Up',
  },
  pet_accessories: {
    product: 'Pet Accessory', products: 'Pet Accessories',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Pet Style Quiz', custom_order: 'Custom Pet Accessory',
    shop: 'Pet Accessories Store', book_appointment: 'Book Pick Up',
  },
  acrylic_art: {
    product: 'Acrylic Piece', products: 'Acrylic Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom Acrylic Order',
    shop: 'Acrylic Art Store', book_appointment: 'Book Pick Up',
  },
  handmade_stationery: {
    product: 'Stationery Item', products: 'Stationery Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom Stationery Order',
    shop: 'Stationery Store', book_appointment: 'Book Pick Up',
  },
  phone_case: {
    product: 'Phone Case', products: 'Phone Case Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom Phone Case',
    shop: 'Phone Case Store', book_appointment: 'Book Pick Up',
  },
  tumbler_mug: {
    product: 'Tumbler / Mug', products: 'Tumbler & Mug Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom Tumbler / Mug',
    shop: 'Tumbler Store', book_appointment: 'Book Pick Up',
  },
  keychain: {
    product: 'Keychain', products: 'Keychain Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: null, custom_order: 'Custom Keychain Order',
    shop: 'Keychain Store', book_appointment: 'Book Pick Up',
  },
  fridge_magnet: {
    product: 'Fridge Magnet', products: 'Magnet Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: null, custom_order: 'Custom Magnet Order',
    shop: 'Magnet Store', book_appointment: 'Book Pick Up',
  },
  wedding_favors: {
    product: 'Wedding Favor', products: 'Wedding Favors',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: null, custom_order: 'Custom Wedding Favor Order',
    shop: 'Wedding Favors Store', book_appointment: 'Book Pick Up',
  },
  kids_accessories: {
    product: 'Kids Accessory', products: 'Kids Accessories',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: null, custom_order: 'Custom Kids Accessory',
    shop: 'Kids Accessories Store', book_appointment: 'Book Pick Up',
  },
  baby_gifts: {
    product: 'Baby Gift', products: 'Baby Gift Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: null, custom_order: 'Custom Baby Gift',
    shop: 'Baby Gift Store', book_appointment: 'Book Pick Up',
  },
  custom_led_gifts: {
    product: 'LED Gift', products: 'LED Gift Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom LED Gift',
    shop: 'LED Gift Store', book_appointment: 'Book Pick Up',
  },
  handmade_perfume: {
    product: 'Perfume', products: 'Perfume Collection',
    delivery_option: 'Home Delivery', appointment: 'Scent Consultation',
    quiz_name: 'Scent Finder Quiz', custom_order: 'Custom Perfume Order',
    shop: 'Perfume Boutique', book_appointment: 'Book Scent Consultation',
  },
  organic_beauty: {
    product: 'Beauty Product', products: 'Beauty Collection',
    delivery_option: 'Home Delivery', appointment: 'Skin Consultation',
    quiz_name: 'Skin Type Quiz', custom_order: 'Custom Beauty Order',
    shop: 'Beauty Store', book_appointment: 'Book Consultation',
  },
  handmade_bags: {
    product: 'Bag', products: 'Bag Collection',
    delivery_option: 'Home Delivery', appointment: 'Try & Buy',
    quiz_name: 'Style Quiz', custom_order: 'Custom Bag Order',
    shop: 'Bag Store', book_appointment: 'Book Try & Buy',
  },
  beaded_jewellery: {
    product: 'Beaded Jewellery', products: 'Beaded Collection',
    delivery_option: 'Home Delivery', appointment: 'Try & Buy',
    quiz_name: 'Style Quiz', custom_order: 'Custom Beaded Jewellery',
    shop: 'Beaded Jewellery Store', book_appointment: 'Book Try & Buy',
  },
  silver_jewellery: {
    product: 'Silver Jewellery', products: 'Silver Collection',
    delivery_option: 'Home Delivery', appointment: 'Try & Buy',
    quiz_name: 'Jewellery Style Quiz', custom_order: 'Custom Silver Jewellery',
    shop: 'Silver Jewellery Store', book_appointment: 'Book Try & Buy',
  },
  bridal_jewellery_rental: {
    product: 'Bridal Jewellery Set', products: 'Bridal Jewellery Collection',
    delivery_option: 'Home Delivery', appointment: 'Try & Buy',
    quiz_name: 'Bridal Style Quiz', custom_order: 'Custom Bridal Set',
    shop: 'Bridal Jewellery Store', book_appointment: 'Book Try & Buy',
  },
  artificial_flower_decor: {
    product: 'Floral Decor Piece', products: 'Floral Decor Collection',
    delivery_option: 'Home Delivery', appointment: 'Consultation',
    quiz_name: 'Decor Style Quiz', custom_order: 'Custom Floral Decor',
    shop: 'Floral Decor Store', book_appointment: 'Book Consultation',
  },
  festive_decor: {
    product: 'Decor Piece', products: 'Festive Decor Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Decor Style Quiz', custom_order: 'Custom Decor Order',
    shop: 'Festive Decor Store', book_appointment: 'Book Pick Up',
  },
  home_styling: {
    product: 'Decor Piece', products: 'Home Styling Collection',
    delivery_option: 'Home Delivery', appointment: 'Styling Consultation',
    quiz_name: 'Decor Style Quiz', custom_order: 'Custom Decor Order',
    shop: 'Home Styling Brand', book_appointment: 'Book Styling Consultation',
  },
  diy_craft_kits: {
    product: 'DIY Kit', products: 'DIY Kit Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom DIY Kit',
    shop: 'DIY Kit Store', book_appointment: 'Book Pick Up',
  },
  embroidery_art: {
    product: 'Embroidery Piece', products: 'Embroidery Collection',
    delivery_option: 'Home Delivery', appointment: 'Workshop',
    quiz_name: 'Style Quiz', custom_order: 'Custom Embroidery Order',
    shop: 'Embroidery Store', book_appointment: 'Book Workshop',
  },
  fabric_painting: {
    product: 'Fabric Art Piece', products: 'Fabric Art Collection',
    delivery_option: 'Home Delivery', appointment: 'Workshop',
    quiz_name: 'Style Quiz', custom_order: 'Custom Fabric Art',
    shop: 'Fabric Art Store', book_appointment: 'Book Workshop',
  },
  handmade_bookmarks: {
    product: 'Bookmark', products: 'Bookmark Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom Bookmark Order',
    shop: 'Bookmark Store', book_appointment: 'Book Pick Up',
  },
  miniature_art: {
    product: 'Miniature Piece', products: 'Miniature Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom Miniature Order',
    shop: 'Miniature Art Store', book_appointment: 'Book Pick Up',
  },
  bottle_art: {
    product: 'Bottle Art Piece', products: 'Bottle Art Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom Bottle Art',
    shop: 'Bottle Art Store', book_appointment: 'Book Pick Up',
  },
  handmade_frames: {
    product: 'Frame', products: 'Frame Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom Frame Order',
    shop: 'Frame Store', book_appointment: 'Book Pick Up',
  },
  couple_gifts: {
    product: 'Couple Gift', products: 'Couple Gift Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Gift Finder Quiz', custom_order: 'Custom Couple Gift',
    shop: 'Couple Gifts Store', book_appointment: 'Book Pick Up',
  },
  anime_merchandise: {
    product: 'Anime Merch Item', products: 'Anime Merch Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Fandom Quiz', custom_order: 'Custom Merch Order',
    shop: 'Anime Merch Store', book_appointment: 'Book Pick Up',
  },
  handmade_plushies: {
    product: 'Plushie', products: 'Plushie Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom Plushie Order',
    shop: 'Plushie Store', book_appointment: 'Book Pick Up',
  },
  wedding_hamper: {
    product: 'Wedding Hamper', products: 'Wedding Hampers',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: null, custom_order: 'Custom Wedding Hamper',
    shop: 'Wedding Hamper Store', book_appointment: 'Book Pick Up',
  },
  luxury_gift_box: {
    product: 'Luxury Gift Box', products: 'Luxury Gift Boxes',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Gift Finder Quiz', custom_order: 'Custom Luxury Gift Box',
    shop: 'Luxury Gift Store', book_appointment: 'Book Pick Up',
  },
  car_decor: {
    product: 'Car Decor Item', products: 'Car Decor Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom Car Decor',
    shop: 'Car Decor Store', book_appointment: 'Book Pick Up',
  },
  spiritual_decor: {
    product: 'Spiritual Decor Piece', products: 'Spiritual Decor Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom Spiritual Decor',
    shop: 'Spiritual Decor Store', book_appointment: 'Book Pick Up',
  },
  puja_decor: {
    product: 'Puja Decor Item', products: 'Puja Decor Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: null, custom_order: 'Custom Puja Decor Order',
    shop: 'Puja Decor Store', book_appointment: 'Book Pick Up',
  },
  resin_gifts: {
    product: 'Resin Gift', products: 'Resin Gift Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom Resin Gift',
    shop: 'Resin Gift Store', book_appointment: 'Book Pick Up',
  },
  handmade_trinkets: {
    product: 'Trinket', products: 'Trinket Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Style Quiz', custom_order: 'Custom Trinket Order',
    shop: 'Trinket Store', book_appointment: 'Book Pick Up',
  },
  aesthetic_lifestyle: {
    product: 'Lifestyle Product', products: 'Lifestyle Collection',
    delivery_option: 'Home Delivery', appointment: 'Pick Up',
    quiz_name: 'Aesthetic Style Quiz', custom_order: 'Custom Order',
    shop: 'Lifestyle Store', book_appointment: 'Book Pick Up',
  },
  luxury_boutique: {
    product: 'Luxury Item', products: 'Luxury Collection',
    delivery_option: 'Home Delivery', appointment: 'Private Viewing',
    quiz_name: 'Style Quiz', custom_order: 'Custom Luxury Order',
    shop: 'Luxury Boutique', book_appointment: 'Book Private Viewing',
  },
  generic: {
    product: 'Product', products: 'Products',
    delivery_option: 'Delivery', appointment: 'Appointment',
    quiz_name: 'Style Quiz', custom_order: 'Custom Order',
    shop: 'Shop', book_appointment: 'Book Appointment',
  },
};

export const getLabels = (businessType) => {
  return BUSINESS_TYPE_LABELS[businessType] || BUSINESS_TYPE_LABELS.generic;
};

// Human-readable display names for the signup dropdown
export const BUSINESS_TYPE_OPTIONS = [
  { value: 'nail_art',               label: 'Nail Artist' },
  { value: 'mehendi',                label: 'Mehendi Artist' },
  { value: 'cake',                   label: 'Cake Shop' },
  { value: 'makeup_artist',          label: 'Makeup Artist' },
  { value: 'handmade_jewellery',     label: 'Handmade Jewellery Brand' },
  { value: 'artificial_jewellery',   label: 'Artificial Jewellery Seller' },
  { value: 'boutique_clothing',      label: 'Boutique Clothing Seller' },
  { value: 'saree_boutique',         label: 'Saree Boutique' },
  { value: 'lehenga_boutique',       label: 'Lehenga Boutique' },
  { value: 'ethnic_wear',            label: 'Ethnic Wear Designer' },
  { value: 'tattoo_artist',          label: 'Tattoo Artist' },
  { value: 'personalized_gifts',     label: 'Personalized Gift Store' },
  { value: 'wedding_decorator',      label: 'Wedding Decorator' },
  { value: 'home_baker',             label: 'Home Baker' },
  { value: 'hair_stylist',           label: 'Hair Stylist' },
  { value: 'eyelash_artist',         label: 'Eyelash Extension Artist' },
  { value: 'bridal_stylist',         label: 'Bridal Stylist' },
  { value: 'handmade_crafts',        label: 'Handmade Craft Store' },
  { value: 'resin_art',              label: 'Resin Art Business' },
  { value: 'crochet',                label: 'Crochet Business' },
  { value: 'candle_brand',           label: 'Candle Brand' },
  { value: 'handmade_soap',          label: 'Handmade Soap Brand' },
  { value: 'handmade_skincare',      label: 'Handmade Skincare Brand' },
  { value: 'balloon_decoration',     label: 'Balloon Decoration Service' },
  { value: 'florist',                label: 'Florist' },
  { value: 'event_planner',          label: 'Event Planner' },
  { value: 'chocolate_bouquet',      label: 'Chocolate Bouquet Business' },
  { value: 'return_gifts',           label: 'Return Gift Business' },
  { value: 'invitation_designer',    label: 'Invitation Designer' },
  { value: 'custom_nameplate',       label: 'Custom Nameplate Seller' },
  { value: 'pottery',                label: 'Pottery Seller' },
  { value: 'clay_art',               label: 'Clay Art Business' },
  { value: 'digital_portrait',       label: 'Digital Portrait Artist' },
  { value: 'home_decor',             label: 'Handmade Home Decor Seller' },
  { value: 'wall_decor',             label: 'Wall Decor Business' },
  { value: 'macrame',                label: 'Macrame Decor Seller' },
  { value: 'furniture_decor',        label: 'Handmade Furniture Decor Brand' },
  { value: 'fashion_accessories',    label: 'Fashion Accessories Seller' },
  { value: 'handbag_brand',          label: 'Handbag Brand' },
  { value: 'bridal_accessories',     label: 'Bridal Accessories Seller' },
  { value: 'custom_footwear',        label: 'Custom Footwear Brand' },
  { value: 'watch_accessories',      label: 'Watch & Accessories Seller' },
  { value: 'dessert_business',       label: 'Dessert Business' },
  { value: 'donut_shop',             label: 'Donut Shop' },
  { value: 'macaron_business',       label: 'Macaron Business' },
  { value: 'mithai_sweets',          label: 'Mithai & Sweet Boutique' },
  { value: 'gift_hamper',            label: 'Gift Hamper Business' },
  { value: 'festival_gifts',         label: 'Festival Gift Seller' },
  { value: 'rakhi_business',         label: 'Rakhi Business' },
  { value: 'diwali_hamper',          label: 'Diwali Hamper Seller' },
  { value: 'scrapbook',              label: 'Scrapbook Business' },
  { value: 'memory_album',           label: 'Memory Album Creator' },
  { value: 'handmade_toys',          label: 'Handmade Toy Seller' },
  { value: 'pet_accessories',        label: 'Pet Accessories Brand' },
  { value: 'acrylic_art',            label: 'Acrylic Art Business' },
  { value: 'handmade_stationery',    label: 'Handmade Stationery Brand' },
  { value: 'phone_case',             label: 'Phone Case Customization Business' },
  { value: 'tumbler_mug',            label: 'Tumbler & Mug Customization Store' },
  { value: 'keychain',               label: 'Handmade Keychain Seller' },
  { value: 'fridge_magnet',          label: 'Fridge Magnet Business' },
  { value: 'wedding_favors',         label: 'Wedding Favors Business' },
  { value: 'kids_accessories',       label: 'Kids Accessories Brand' },
  { value: 'baby_gifts',             label: 'Baby Gift Business' },
  { value: 'custom_led_gifts',       label: 'Custom LED Gift Business' },
  { value: 'handmade_perfume',       label: 'Handmade Perfume Brand' },
  { value: 'organic_beauty',         label: 'Organic Beauty Product Seller' },
  { value: 'handmade_bags',          label: 'Handmade Bag Seller' },
  { value: 'beaded_jewellery',       label: 'Beaded Jewellery Business' },
  { value: 'silver_jewellery',       label: 'Silver Jewellery Seller' },
  { value: 'bridal_jewellery_rental',label: 'Bridal Jewellery Rental Business' },
  { value: 'artificial_flower_decor',label: 'Artificial Flower Decor Seller' },
  { value: 'festive_decor',          label: 'Festive Decor Business' },
  { value: 'home_styling',           label: 'Home Styling Decor Brand' },
  { value: 'diy_craft_kits',         label: 'DIY Craft Kit Seller' },
  { value: 'embroidery_art',         label: 'Embroidery Art Business' },
  { value: 'fabric_painting',        label: 'Fabric Painting Business' },
  { value: 'handmade_bookmarks',     label: 'Handmade Bookmark Seller' },
  { value: 'miniature_art',          label: 'Miniature Art Business' },
  { value: 'bottle_art',             label: 'Customized Bottle Art Business' },
  { value: 'handmade_frames',        label: 'Handmade Frame Business' },
  { value: 'couple_gifts',           label: 'Couple Gift Business' },
  { value: 'anime_merchandise',      label: 'Anime Merchandise Creator' },
  { value: 'handmade_plushies',      label: 'Handmade Plushie Business' },
  { value: 'wedding_hamper',         label: 'Wedding Hamper Business' },
  { value: 'luxury_gift_box',        label: 'Luxury Gift Box Business' },
  { value: 'car_decor',              label: 'Car Hanging Decor Seller' },
  { value: 'spiritual_decor',        label: 'Handmade Spiritual Decor Seller' },
  { value: 'puja_decor',             label: 'Festive Puja Decor Seller' },
  { value: 'resin_gifts',            label: 'Customized Resin Gift Seller' },
  { value: 'handmade_trinkets',      label: 'Handmade Trinket Business' },
  { value: 'aesthetic_lifestyle',    label: 'Aesthetic Lifestyle Product Seller' },
  { value: 'luxury_boutique',        label: 'Small Luxury Boutique Brand' },
  { value: 'generic',                label: 'Other' },
];
